name: votu_table
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python >=3.7
  - samtools =1.10
  - bwa =0.7.17
  - perl >=5
  - mummer =3.23
  - pandas >=1
  - biopython =1.77
