FROM continuumio/miniconda3:latest
LABEL author="carisdak@hawaii.edu"

RUN apt-get update && apt-get install -y git
COPY conda_env.yml /
RUN conda env create -f /conda_env.yml && conda clean -a

#=================================================#
#============ stampede-clustergenomes ============#
#=================================================#

RUN git clone https://bitbucket.org/MAVERICLab/stampede-clustergenomes.git \
    && mv stampede-clustergenomes /opt

ENV PATH /opt/conda/envs/votu_table/bin:/opt/stampede-clustergenomes/bin:$PATH
